### ISSUE TITLE
Refactoring of getProperties as mentioned in the comment

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [avTranscoder/avTranscoder#140]
https://github.com/avTranscoder/avTranscoder/pull/139#commitcomment-10981486

**Comment by cchampet** [comment]
I do not understand why but with this update, I cannot call the 2 methods __asVector__ from a derived class of __StreamProperties__.
```
PropertyVector StreamProperties::asVector() const
{
    PropertyVector propertyVector;
    return asVector(propertyVector);
}

PropertyVector& StreamProperties::asVector(PropertyVector& data) const
{
    addProperty(data, ...);
    addProperty(data, ...);
    return data;
}

PropertyVector& AudioProperties::asVector(PropertyVector& data) const
{
    addProperty(data, ...);
    addProperty(data, ...);
    return data;
}
```
And this does not work:
```
const AudioProperties& audioProperties;
PropertyVector properties = audioProperties.asVector();
```
Compilation error is:
note: virtual avtranscoder::PropertyVector& avtranscoder::AudioProperties::asVector(avtranscoder::PropertyVector&) const
     PropertyVector& asVector(PropertyVector& data) const;
                     ^
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/properties/AudioProperties.hpp:82:21: note:   candidate expects 1 argument, 0 provided

**Comment by cchampet** [comment]
Apparently, the 2 methods cannot have the same name. So the new one is called fillVector.
