### ISSUE TITLE
Can we have json output for avmeta tool ?

### ISSUE THREAD

**Issue by cchampet** [avTranscoder/avTranscoder#165]
<a href="https://github.com/mguiral"><img src="https://avatars.githubusercontent.com/u/1543779?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mguiral](https://github.com/mguiral)**
_Wednesday Aug 26, 2015 at 08:42 GMT_
_Originally opened as https://github.com/mikrosimage/avTranscoder/issues/225_

----

**Comment by cchampet** [comment]
<a href="https://github.com/cchampet"><img src="https://avatars.githubusercontent.com/u/2589095?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cchampet](https://github.com/cchampet)**
_Monday Sep 28, 2015 at 12:25 GMT_

----

https://github.com/nlohmann/json

**Comment by MarcAntoine-Arnaud** [comment]
I think a simple json writer can be write in C++.
You can an example in C++11 here: https://github.com/gchatelet/light_sequence_parser/blob/master/app/JsonWriter.h
Better to don't have any dependency for that.

**Comment by cchampet** [comment]
Agreed. Thx for the link, this code seems great for what we need :ok_hand:
