### ISSUE TITLE
Ghost threads with java binding

### ISSUE THREAD

**Issue by mguiral** [avTranscoder/avTranscoder#181]
There is a problem with the InputFile.analyse method when level parameter equals eAnalyseLevelFirstGop (the default value when no parameter is specified) : several threads are created and are not killed.

For example, in our application, metadatas extraction of 5 medias create 20 ghost threads

**Comment by cchampet** [comment]
https://github.com/avTranscoder/avTranscoder/blob/develop/src/AvTranscoder/mediaProperty/VideoProperties.cpp#L540
