### ISSUE TITLE
0 value for -t or -f pythumbnail command parameter

### ISSUE THREAD

**Issue by mguiral** [avTranscoder/avTranscoder#185]
This create empty thumbnail. The problem occur when i use 0 value with the method InputFile.seekAtTime

**Comment by cchampet** [comment]
I cannot reproduce the bug...

I use v0.6.1.
pythumbnail does not seek if 0 is passed to -t/-f parameter.
And even if I force to seek at 0, it works.
I tested it with dxn and jpg input files.

What version do you use?
What is your input?

**Comment by cchampet** [comment]
It also works with v0.5.11

**Comment by cchampet** [comment]
Cannot be reproduce in the latest version. Won't fix for now. Feel free to reopen it if you need to.
